version: "3.7"

services:
  memcached:
    image: memcached:alpine
    container_name: xampp-cloud-memcached
    ports:
      - 11211:11211
    networks:
      - xampp-cloud
      
  apache2:
    build: 
      context: ./images/apache2
      args:
        - PHP_VERSION=${PHP_VERSION}
    environment:
      - PHP_VERSION=${PHP_VERSION}
    container_name: xampp-cloud-apache2
    volumes:
      - ../src:/var/www/html
      - ./images/apache2/virtual-hosts.conf:/etc/apache2/sites-enabled/virtual-hosts.conf:rw
      - ./images/apache2/php.ini:/usr/local/etc/php/php.ini:rw
      - ./volumes/logs/:/var/log
    ports:
      - 80:80
      - 443:443
    networks:
      - xampp-cloud
      
  mariadb:
    build: 
      context: ./images/mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
    container_name: xampp-cloud-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_USER: root
    restart: on-failure
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    networks:
      - xampp-cloud

  mysql:
    build: 
      context: ./images/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: xampp-cloud-mysql
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - xampp-cloud

  phpmyadmin:
    container_name: xampp-cloud-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=3600
    networks:
      - xampp-cloud
      
networks:
  xampp-cloud:
    name: xampp-cloud-network
