#!/bin/bash
if [ $# -eq 0 ] ; then
    container_name=""
else
    container_name=$1
fi

# Show the logs for the specified container
if [[ "$container_name" == "php" ]]; then
    sudo docker logs "xampp-cloud-${container_name}-74" --follow
    sudo docker logs "xampp-cloud-${container_name}-81" --follow
    sudo docker logs "xampp-cloud-${container_name}-82" --follow
elif [[ "$container_name" == "nginx" ]]; then
    sudo docker logs "xampp-cloud-${container_name}" --follow
elif [[ "$container_name" == "elastic" ]]; then
    sudo docker logs "xampp-cloud-elastic" --follow
else
    if [ -z "$container_name" ]; then
       sudo docker-compose logs --follow 
    else
       sudo docker logs "$container_name" --follow
    fi
fi
